apiVersion: v2
name: hello-app
description: A simple Hello World microservice for DevOps assignment
type: application
version: 1.0.0
appVersion: "1.0.0"
maintainers:
  - name: S Sidharth
    email: ssidharthsmail@gmail.com
keywords:
  - nodejs
  - microservice
  - devops
home: https://github.com/ssidharths/idurar-erp-crm
sources:
  - https://github.com/ssidharths/idurar-erp-crm
